services:
  geoserver:
    image: kartoza/geoserver:2.27.0
    container_name: geoserver
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
      RESET_ADMIN_CREDENTIALS: ${RESET_ADMIN_CREDENTIALS}
      GEOSERVER_DATA_DIR: ${GEOSERVER_DATA_DIR}
      ENABLE_JSONP: ${ENABLE_JSONP}
      MAX_FILTER_RULES: ${MAX_FILTER_RULES}
      OPTIMIZE_LINE_WIDTH: ${OPTIMIZE_LINE_WIDTH}
      GEOSERVER_PROXY_BASE_URL: ${GEOSERVER_PROXY_BASE_URL}
      GEOSERVER_CSRF_WHITELIST: ${GEOSERVER_CSRF_WHITELIST}
      HTTP_SCHEME: ${HTTP_SCHEME}
      JAVA_OPTS: ${JAVA_OPTS}
      GEOSERVER_XSTREAM_WHITELIST: ${GEOSERVER_XSTREAM_WHITELIST}
      POSTGIS_HOST: ${POSTGIS_HOST}
      POSTGIS_PORT: ${POSTGIS_PORT}
      POSTGIS_DB: ${POSTGIS_DB}
      POSTGIS_USER: ${POSTGIS_USER}
      POSTGIS_PASSWORD: ${POSTGIS_PASSWORD}
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./plugins:/opt/geoserver/webapps/geoserver/WEB-INF/lib/
      - ./server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./config/security/csp.xml:/opt/geoserver/data_dir/security/csp.xml:ro
    networks:
      - geonetwork

volumes:
  geoserver_data:


networks:
  geonetwork:
    driver: bridge
